### ISSUE TITLE
Any chance you can include a  react hooks example?

### ISSUE THREAD

**Issue by peterpme** [alexfedoseev/re-debouncer#4]
Hey there,

I've been trying to get this library to work correctly but I'm struggling with hooks. I'm probably just an idiot, but is there any easy example I can take a look at?

Thanks!

**Comment by alex35mil** [comment]
Hey, I updated README with the hooks example. Check it out and let me know if you have any questions.

**Comment by peterpme** [comment]
Hey @alexfedoseev I really appreciate it! This is what I was thinking but I wasn't sure 😃

This is probably outside the scope of the project, but it could solve the problem for others, we could also have an example where the Api request lives above the input itself.

A question I have for myself (will test) is whether I should have the debouncer in each every individual input along with setState or if I should hoist the debouncer up to the parent component that handles the request and just have an internal state for the input itself.

**Comment by alex35mil** [comment]
> This is probably outside the scope of the project, but it could solve the problem for others, we could also have an example where the Api request lives above the input itself.

Believe it or not, but this is what I initially wanted to do, but. In the apps I'm working on requests look as following:

```reason
Api.doThing()
->Promise.wait(
  fun
  | Ok(res) => SucceedRequest(res)->dispatch
  | Error(error) => FailRequest(res)->dispatch
)
```

But then I realized that official `Js.Promise` bindings are different (and if used, encourage using `catch` which should be avoided in the application code by eliminating it in the abstraction over network transport) and I didn't really wanted to go into something unrelated to what this lib does. Probably, it makes sense to add working example (not in README) to show just this.

> A question I have for myself (will test) is whether I should have the debouncer in each every individual input along with setState or if I should hoist the debouncer up to the parent component that handles the request and just have an internal state for the input itself.

I usually do the latter, otherwise `Input` component does a bit more assumptions then it should, at my taste. But it depends on app ofc and it might make sense to add abstraction layer over primitive `Input` which implements debouncing.
